### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by Gattermeier** [BradLyman/DarwinBots.Js#1]
How do you actually run the app?

**Comment by BradLyman** [comment]
There is a very, very basic web interface at http://bradlyman.github.io/DarwinBots.js-Client/#/speciesLoader. However, the compiler does not support the full DB dna language and will fail silently if invalid code is used (which is a terrible user experience).

Some code that will work, if you save it in a text file and upload it, is:

```
cond
start
  1 *.up add .up store
stop

cond
  *.up 5 >
start
  *.up .right store
stop

cond
  *.right 10 >
start
  *.right 3 sub .body store
stop
```

I am in the middle of updating the compiler to provide better error reporting -- and along the way I made some slight changes to the language. This is being done on the ast branch if you are curious.

Thanks for the interest, this is definitely still a project in its infancy and I am always open to suggestions!
